### ISSUE TITLE
My node not continue sync 

### ISSUE THREAD

**Issue by QuocHa2000** [wormholes-org/wormholes#100]
After installing new version, my node not continue sync and my credibility decrease and decrease, i tried restart my node but it not work 

<img width="554" alt="image" src="https://user-images.githubusercontent.com/55241861/212107957-0501fc07-af02-4a24-a8be-9884dbf3c1d5.png">
<img width="815" alt="image" src="https://user-images.githubusercontent.com/55241861/212108013-549d5e74-42ef-4766-b77b-be29a65e6569.png">

**Comment by uniquevme** [comment]
Please submit your questions and actions according to the https://github.com/wormholes-org/wormholes/issues/73, so that we can find the problem.

**Comment by uniquevme** [comment]
Please submit your questions and actions according to the [template](https://github.com/wormholes-org/wormholes/issues/73,) so that we can find the problem.

**Comment by t2dk49580** [comment]
When the node is powered off or exited or restarted abnormally due to other reasons, some programs have errors in writing the database, resulting in the loss of block status data. The final result is that the block is no longer growing. We have repeated this problem and repaired it through v0.11.7
