### ISSUE TITLE
 i have peer and number of node connection but my credit is going down

### ISSUE THREAD

**Issue by abdikonoha** [wormholes-org/wormholes#101]
#### System information

Wormholes version: `wormholes version`
OS & Version: linux
![credit](https://user-images.githubusercontent.com/106908636/212158103-f9a0e1a4-1fd7-4414-b024-4ab35b5f12da.PNG)
![credit 2](https://user-images.githubusercontent.com/106908636/212158202-56b0aa52-5b48-4e5d-b4eb-3dac78b523c1.PNG)
![credit](https://user-images.githubusercontent.com/106908636/212158209-267b8218-dcff-41fb-afbd-5d861b09c353.PNG)

Commit hash : (if `develop`)

why sir ? my credit is going down . erb income does not increase.

When submitting logs: please submit them as text and not screenshots.

**Comment by uniquevme** [comment]
Participation consensus failure, credit decreased by 10, erb will not increase.
note：
1. The node must be online.
2. Check whether the nodekey and private key are the same.
