### ISSUE TITLE
My wallet is not increase ERB since yesterday

### ISSUE THREAD

**Issue by fx5testnet** [wormholes-org/wormholes#103]
Dear Admin,
My wallet is not increase ERB since yesterday. Can you please check this wallet: 0xf85Ce0E8d096876B42Ff191d8d49B76Ed11df6CC. Thanks
#### System information

Wormholes version: `wormholes version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by 1kangk** [comment]
First check that the private key you use to run the node is the same account。I checked your current weight is only 50, too low will affect the ERB bonus。
