### ISSUE TITLE
My node keeps stopping.

### ISSUE THREAD

**Issue by SaitomoPM** [wormholes-org/wormholes#105]
It has been 48 hours, my node keeps stopping. I deleted everything and docker, reinstalled the node then it works but when it catches the block, it suddenly stops. I tried this way many times but nothing changed, again no peer. I also recovered my points but same here.

Wallet address: 0x9528B00C6795BE25046fA1A1c5fb598bb94C5EA0

Logs:

![image](https://user-images.githubusercontent.com/116270907/212527332-7c820ba5-077a-49b8-81db-aeb174592984.jpeg)

**Comment by t2dk49580** [comment]
This problem may be related to docker. Please try again using source code compilation
https://www.wormholes.com/docs
