### ISSUE TITLE
stuck block peer

### ISSUE THREAD

**Issue by cindillicius** [wormholes-org/wormholes#107]
my node stuck and make my credibility down
![image](https://user-images.githubusercontent.com/117460658/213140268-daba4ba6-9108-4b8b-878e-6b4541c7f478.png)
and when i restart, i got 0
![image](https://user-images.githubusercontent.com/117460658/213140731-2abe311b-8c09-4a21-96f7-489bffc26959.png)

**Comment by t2dk49580** [comment]
Consolidation problem handling: https://github.com/wormholes-org/wormholes/issues/113

**Comment by t2dk49580** [comment]
When the node is powered off or exited or restarted abnormally due to other reasons, some programs have errors in writing the database, resulting in the loss of block status data. The final result is that the block is no longer growing. We have repeated this problem and repaired it through v0.11.7
