### ISSUE TITLE
Credit score always decrease

### ISSUE THREAD

**Issue by Whalealert** [wormholes-org/wormholes#108]
![image-1](https://user-images.githubusercontent.com/108969749/213157271-7cc5728c-e98a-4b2f-9de3-70ac0b2fcfb8.png)

**Comment by t2dk49580** [comment]
Thank you for your feedback. The current algorithm is that all verifiers who participate in the consensus and do not block out will be punished, but after the next block out, the weight can be restored to normal. This problem will be optimized in the next version v0.12, and the weight can be restored immediately.
