### ISSUE TITLE
NODE 4/8 stuck and Credit getting lower 

### ISSUE THREAD

**Issue by samkurniawan100** [wormholes-org/wormholes#109]
#### System information

Wormholes version: `wormholes version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

node 8545
Block height of the whole network: 247561
Number of node connections: 21
Block height of the current peer: 247561

since 16 monday

**Comment by t2dk49580** [comment]
Thank you for your feedback. The current algorithm is that all verifiers who participate in the consensus and do not block out will be punished, but after the next block out, the weight can be restored to normal. This problem will be optimized in the next version v0.12, and the weight can be restored immediately.
