### ISSUE TITLE
Stuck block everyday

### ISSUE THREAD

**Issue by blacktokyo96** [wormholes-org/wormholes#110]
#### System information

Wormholes version: `wormholes v0.11.6`
OS & Version: Linux

I have a stuck block all the time, i 
![Screenshot_20230119_060346](https://user-images.githubusercontent.com/86566948/213315020-f1aae059-aa8b-4b9b-af14-adbf17d6280d.png)
reinstalled and the block runs normally but the block will occur again and again

**Comment by t2dk49580** [comment]
Consolidation problem handling: https://github.com/wormholes-org/wormholes/issues/113

**Comment by t2dk49580** [comment]
When the node is powered off or exited or restarted abnormally due to other reasons, some programs have errors in writing the database, resulting in the loss of block status data. The final result is that the block is no longer growing. We have repeated this problem and repaired it through v0.11.7
