### ISSUE TITLE
My node is stuck for 2 days 

### ISSUE THREAD

**Issue by vietngtuna** [wormholes-org/wormholes#111]
#### System information

Wormholes version: Wormholes version lastest
OS & Version: Linux

#### Expected behaviour
100% synced

#### Actual behaviour
stuck for 2 days

![image](https://user-images.githubusercontent.com/111576237/213467237-d9686804-751d-47db-ae3c-ed4d53476c30.png)

**Comment by t2dk49580** [comment]
Consolidation problem handling: https://github.com/wormholes-org/wormholes/issues/113
