### ISSUE TITLE
stuck 0/0 7 days

### ISSUE THREAD

**Issue by yasdinursan** [wormholes-org/wormholes#112]
![Screenshot_2023-01-19-22-08-56-790_com server auditor ssh client](https://user-images.githubusercontent.com/36165323/213479503-1376bb1e-bb5a-44ff-9170-e4020a016ebe.jpg)

**Comment by t2dk49580** [comment]
At present, your node has not found a peer node, so it cannot be synchronized. Please change the machine and try again
