### ISSUE TITLE
My node stucks everyday. I sycn my node yesterday it broken today again

### ISSUE THREAD

**Issue by airdrp** [wormholes-org/wormholes#113]
![IMG_20230121_112645](https://user-images.githubusercontent.com/98715676/213858767-64f192af-d342-44a4-8d67-b29799084ace.jpg)

**Comment by t2dk49580** [comment]
Consolidation problem handling: https://github.com/wormholes-org/wormholes/issues/113

**Comment by t2dk49580** [comment]
When the node is powered off or exited or restarted abnormally due to other reasons, some programs have errors in writing the database, resulting in the loss of block status data. The final result is that the block is no longer growing. We have repeated this problem and repaired it through v0.11.7
