### ISSUE TITLE
node is stuck, my node got 50 connected, but the peers stuck,restart not solving the issue

### ISSUE THREAD

**Issue by BrianBathory98** [wormholes-org/wormholes#114]
#### System information

Wormholes version: `v 0.10.3`
OS & Version: Linux

#### Backtrace

````
bash ./monitor.sh
````

stuck on
Block height of the whole network: 267623
Number of node connections: 50
Block height of the current peer: 246003

my peer

ERROR[01-21|09:46:37.375] handlers.go eth.handleWormhole handleWormhole.normalblock err=nil
ERROR[01-21|09:46:37.376] handlers.go eth.handleWormhole handleWormhole.normalblock err=nil
ERROR[01-21|09:46:37.384] handlers.go eth.handleWormhole handleWormhole.normalblock err=nil
ERROR[01-21|09:46:37.390] handlers.go eth.handleWormhole handleWormhole.normalblock err=nil
ERROR[01-21|09:46:37.391] handlers.go eth.handleWormhole handleWormhole.normalblock err=nil
ERROR[01-21|09:46:37.394] handlers.go eth.handleWormhole handleWormhole.normalblock err=nil

**Comment by t2dk49580** [comment]
Consolidation problem handling: https://github.com/wormholes-org/wormholes/issues/113

**Comment by t2dk49580** [comment]
When the node is powered off or exited or restarted abnormally due to other reasons, some programs have errors in writing the database, resulting in the loss of block status data. The final result is that the block is no longer growing. We have repeated this problem and repaired it through v0.11.7
