### ISSUE TITLE
Block stuck

### ISSUE THREAD

**Issue by Robkynd** [wormholes-org/wormholes#115]
My node stuck not move still on block 256309,i try reinstall and restart my node but still stuck around 25xxx.

**Comment by t2dk49580** [comment]
Consolidation problem handling: https://github.com/wormholes-org/wormholes/issues/113

**Comment by t2dk49580** [comment]
When the node is powered off or exited or restarted abnormally due to other reasons, some programs have errors in writing the database, resulting in the loss of block status data. The final result is that the block is no longer growing. We have repeated this problem and repaired it through v0.11.7
