### ISSUE TITLE
Node is stuck

### ISSUE THREAD

**Issue by AkifhanIlgaz** [wormholes-org/wormholes#116]
#### System information

Wormholes version: wormholes v0.11.6
OS & Version: Linux

#### Actual behaviour

My node can't sync. Whenever it reaches the current block, it resets

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by t2dk49580** [comment]
Consolidation problem handling: https://github.com/wormholes-org/wormholes/issues/113

**Comment by t2dk49580** [comment]
When the node is powered off or exited or restarted abnormally due to other reasons, some programs have errors in writing the database, resulting in the loss of block status data. The final result is that the block is no longer growing. We have repeated this problem and repaired it through v0.11.7
