### ISSUE TITLE
not in sync

### ISSUE THREAD

**Issue by Denizakn98** [wormholes-org/wormholes#117]
#### System information

Wormholes version: `Wormholes Chain V.0.11.6
OS & Version: Linux
Commit hash : (if `develop`)

My node hasn't matched for a week. I don't have a peer problem, but very slow block transitions and it's constantly lagging, can you update?

<img width="575" alt="image" src="https://user-images.githubusercontent.com/102308600/214370318-5719d735-af14-4d96-af7e-0431857e28da.png">

<img width="763" alt="image" src="https://user-images.githubusercontent.com/102308600/214370433-f902c193-4c4e-4335-8526-bdb09e23913e.png">

**Comment by t2dk49580** [comment]
Consolidation problem handling: https://github.com/wormholes-org/wormholes/issues/113

**Comment by t2dk49580** [comment]
When the node is powered off or exited or restarted abnormally due to other reasons, some programs have errors in writing the database, resulting in the loss of block status data. The final result is that the block is no longer growing. We have repeated this problem and repaired it through v0.11.7
