### ISSUE TITLE
node stuck ,so credit down

### ISSUE THREAD

**Issue by thenhthang** [wormholes-org/wormholes#118]
#### System information

Wormholes version: wormholes v0.11.6
OS & Version: Linux

root@vmi1157719:~# bash ./wormholes.sh
0 second.
node 8545
Block height of the whole network: 301910
Number of node connections: 50
Block height of the current peer: 249311

**Comment by t2dk49580** [comment]
Thank you for your feedback. The current algorithm is that all verifiers who participate in the consensus and do not block out will be punished, but after the next block out, the weight can be restored to normal. This problem will be optimized in the next version v0.12, and the weight can be restored immediately.

**Comment by t2dk49580** [comment]
When the node is powered off or exited or restarted abnormally due to other reasons, some programs have errors in writing the database, resulting in the loss of block status data. The final result is that the block is no longer growing. We have repeated this problem and repaired it through v0.11.7
