### ISSUE TITLE
credit score

### ISSUE THREAD

**Issue by btkfurkan** [wormholes-org/wormholes#119]
even though my node is up-to-date and I'm always in the up-to-date block. My credit score keeps dropping. The reason for this should not be a new mechanism. After all, I am always up to date.

**Comment by t2dk49580** [comment]
Please submit your question according to the question template, thank you.

issues example:
https://github.com/wormholes-org/wormholes/issues/73

**Comment by t2dk49580** [comment]
The current algorithm is that all verifiers who participate in the consensus and do not block out will be punished, but after the next block out, the weight can be restored to normal. This problem will be optimized in the next version, and the weight can be restored immediately
