### ISSUE TITLE
block stuck at 29524 i did docker restart wormholes but it stuck at 29524

### ISSUE THREAD

**Issue by saiyadav999** [wormholes-org/wormholes#121]
# Rationale

Why should this feature exist?
What are the use-cases?

# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

**Comment by t2dk49580** [comment]
Consolidation problem handling: https://github.com/wormholes-org/wormholes/issues/113

**Comment by t2dk49580** [comment]
When the node is powered off or exited or restarted abnormally due to other reasons, some programs have errors in writing the database, resulting in the loss of block status data. The final result is that the block is no longer growing. We have repeated this problem and repaired it through v0.11.7
