### ISSUE TITLE
Nothing running in my node but port 8545 is in use 

### ISSUE THREAD

**Issue by samkurniawan100** [wormholes-org/wormholes#123]
#### System information

Wormholes version: `wormholes version 0.11`
OS & Version: ubuntu 20.04
Commit hash : (if `develop`)

remove my all node setting and want to re install 
when input private key 

"docker: Error response from daemon: driver failed programming external connectivity on endpoint wormholes (c61f12b6d1f6f1d33f8bb258e4292179eaxxxxxxxxxxxxxxxxxxxxxxxxxf85b84f): Error starting userland proxy: listen tcp4 0.0.0.0:8545: bind: address already in use.
running the container..."

![image](https://user-images.githubusercontent.com/75730821/215787968-0ebe2f9c-e403-4c96-b683-9e390d4178f5.png)

When submitting logs: please submit them as text and not screenshots.

**Comment by xuelongjiang** [comment]
you can use "sudo netstat -ntlp | grep 8545" to find which program use 8545 port
![image](https://user-images.githubusercontent.com/32953331/216262415-474de981-a1c1-484b-b0e2-b0dd4f454400.png)
then use "sudo kill -9 3255452 "(3255452 is the PID found by last command) to  kill the program for release 8545 port.
