### ISSUE TITLE
premision denied on vps

### ISSUE THREAD

**Issue by irulae** [wormholes-org/wormholes#127]
#### System information

Wormholes version: `wormholes version` v1.2
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
im run node on vps cloud but im can not restart my node

#### Actual behaviour
Try delete chaindata and restart Docker

cd /wm/.wormholes/wormholes

rm -rf chaindata

cd

docker restart wormholes

#### Steps to reproduce the behaviour

i look it premision denied on my vps cloud
#### Backtrace

````
[backtra
![ggl](https://user-images.githubusercontent.com/39592248/218915854-c066924c-ab26-4086-9307-740049011a46.PNG)
ce]
````
![node](https://user-images.githubusercontent.com/39592248/218911742-f077d1c8-07fd-4146-80a3-d18e0f79821a.PNG)

When submitting logs: please submit them as text and not screenshots.

**Comment by xuelongjiang** [comment]
del the dir need root's previliage , and need stop the container first:
docker stop wormholes
