### ISSUE TITLE
Block stuck production

### ISSUE THREAD

**Issue by CuanAway** [wormholes-org/wormholes#128]
#### System information

Wormholes version: `v0.12.0`
OS & Version: Linux `v20.04` Docker `v23.0.1`
I have tried resetting the chain data by: 
````
cd /wm/.wormholes/wormholes
rm -rf chaindata
cd
docker restart wormholes
````
But every time the number touches 115000 ++ block nodes can't produce blocks anymore so I'm stuck for days

Validator scan: 
![2023-02-17 (9)](https://user-images.githubusercontent.com/96741114/219597207-9dbbf377-7c2a-47ac-8c71-b605d3354893.png)

When submitting logs: 
![2023-02-17 (7)](https://user-images.githubusercontent.com/96741114/219591681-022b96dc-cf96-481f-a355-53ec4f2dd1ef.png)

**Comment by t2dk49580** [comment]
It is recommended that you try again using source code compilation
https://www.wormholes.com/docs/#/

**Comment by pvsairam** [comment]
I have tried resetting the chain data same as above commands and the block struck at 172211

![Uploading 51187DFF-D016-4F0D-BB4E-F901121636DF.jpeg…]()

**Comment by pvsairam** [comment]
same issue again. how to fix this issue?

![15625E53-D9BE-4297-88B6-5E24B886FBB7](https://user-images.githubusercontent.com/9134015/220602133-58addd54-b3e7-484c-9ae5-1fde92b33b7d.jpeg)

**Comment by Dzeqkon** [comment]
Enable logs to locate the cause of the error.
Run the following command to enable the log function:
sudo docker exec -it wormholes /wm/showlog.sh
The log file path is /wm/.wormholes/node1/logs
Run the following command to disable the log function:
sudo docker exec -it wormholes /wm/noshowlog.sh
