### ISSUE TITLE
Stuck node

### ISSUE THREAD

**Issue by airdrp** [wormholes-org/wormholes#132]
![IMG_20230223_185657](https://user-images.githubusercontent.com/98715676/220961563-73fff443-d4ad-4622-b97e-a1278b174329.jpg)
Node stuvk somewhere all the time. I have been trying and waiting for 2 days

**Comment by pvsairam** [comment]
I have tried stopping the node and restarted it again, still the same issue:

![1AB3C467-99EF-4319-997A-6323EE6B823A](https://user-images.githubusercontent.com/9134015/221074635-346f990d-d7c9-43b6-9825-8e8ec606c02a.jpeg)

**Comment by Dzeqkon** [comment]
No Data cannot be synchronized because the network is not connected

**Comment by pvsairam** [comment]
How to fix this issue? Please let me know

**Comment by Dzeqkon** [comment]
You can try to reboot or reset to get the connection.
If restarting, use docker to restart wormholes
If reset, use the following instructions
docker stop wormholes
docker rm wormholes
rm -rf /wm/.wormholes/*
Then refer to the deployment documentation to redeploy
For example, bash./wormholes_install.sh
Note that you enter the original private key.
