### ISSUE TITLE
Bug White Page

### ISSUE THREAD

**Issue by bakkeieth** [wormholes-org/wormholes#141]
for case tommorow i try to add favorite not function and today i try to adding again, the feature is work
https://discord.com/channels/958607322849112065/1078139881823424632/1087418821826068553

I forget for reported to github.

and now i have case "bug one-click purchase, Immidiate synthesis and income"
When I try to perform the action above and I approve it to the wallet, sometimes it successfully completes the transaction, but sometimes it shows a blank screen which results in the transaction not going through smoothly

**Comment by bakkeieth** [comment]
please check the ss
![Screenshot 2023-03-22 021937](https://user-images.githubusercontent.com/112174339/226719635-5f98f4b1-5b4b-490f-ab55-e78b5196c75d.png)
![Screenshot 2023-03-22 022005](https://user-images.githubusercontent.com/112174339/226719646-d31e34bc-1669-4df0-96f9-feec90cb9545.png)

**Comment by uniquevme** [comment]
Thank you for your feedback, we are working hard.
