### ISSUE TITLE
Main Page Collect & Earn button doesnt work.

### ISSUE THREAD

**Issue by dumanoglu1** [wormholes-org/wormholes#143]
# Rationale

Why should this feature exist?
What are the use-cases?

# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

**Comment by uniquevme** [comment]
1. Refer to ：https://market-2.gitbook.io/meteorite/  https://market-2.gitbook.io/test-rewards-rules/
2. Functional availability.
