### ISSUE TITLE
Validator: No ERB reward and decreasing of credibility for running server

### ISSUE THREAD

**Issue by oleksandrmarkelov** [wormholes-org/wormholes#93]
#### System information

Wormholes version: v0.11.4
OS & Version: Linux

#### Expected behaviour

Server runs 24x7, restarted several times, but credibility descreases every day. Delegated 70K one week ago but still no ERB income.

#### Actual behaviour

No ERB reward and decreasing of credibility

#### Steps to reproduce the behaviour

Validator
0x7140b8BcC1A9ed8885Ff6436C29A9a18A129cD21

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by wormholeslab** [comment]
Your coefficient of account is too low, now it's 20,  the normal value is 70.  if coefficient is too low, it's very hard to be picked as a validator to consensus a block. You can't get rewards if you don't participate to consensus blocks.

**Comment by oleksandrmarkelov** [comment]
I upgraded to 70 already 3 times and it falls to 20 again.

**Comment by oleksandrmarkelov** [comment]
upgraded to v0.11.6. Could you send me some ERB for recovery?

**Comment by oleksandrmarkelov** [comment]
found the issue on my side, when started the node private key has "0x" as prefix
