### ISSUE TITLE
no ERB income

### ISSUE THREAD

**Issue by Cryptoerdo** [wormholes-org/wormholes#96]
#### System information

Wormholes version: v0.11.6
OS & Version: Linux

#### Expected behaviour

 running my node since the beginning of project. my snft income is increasing smoothly.

#### Actual behaviour

when we passed to v0.11.4 my ERB income became zero and dont change anymore. my credibility decreasing very fast. i already recovered 4 or 5 times. private key is same as usual

#### Steps to reproduce the behaviour

validator
0x66b1c3a719B6eDC8531d17318de9AC551B18B1E6

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by 1kangk** [comment]
I checked your account just now, and now there are rewards

**Comment by Cryptoerdo** [comment]
yeap it fixed. like it was waiting for me to write here. thank you
