### ISSUE TITLE
my transactions hang

### ISSUE THREAD

**Issue by alltcoindr** [wormholes-org/wormholes#97]
I'm trying to cancel the remaining transactions in the pending from the transaction history section, I get an error. I reported this situation on discord 2 weeks ago, but there was no response. Now node is running on its current version, but I could not stake the sent tokens because the transaction history is stuck in the pending. my node has been running for 2 weeks to no avail.

**Comment by 1kangk** [comment]
May I have your account address?

**Comment by uniquevme** [comment]
hey sir，Please submit your questions and actions according to the Example template [https://github.com/wormholes-org/wormholes/issues/73], so that we can find the problem.
