### ISSUE TITLE
After update to v0.11.6 node connections still 0

### ISSUE THREAD

**Issue by BBCC88** [wormholes-org/wormholes#98]
After update to v0.11.6 , mine node connections becomes 0 and can't sync any block.
But the version v0.11.4 all correct.
how to resolve this problem?

Mine step:
1. docker stop $(docker ps -aq)
2. docker rm $(docker ps -aq)
3. docker rmi $(docker images -q)
4. rm -rf /wm
5. wget -O wormholes_install.sh https://docker.wormholes.com/wormholes_install.sh && sudo bash wormholes_install.sh

**Comment by 1kangk** [comment]
You can pull up the source code on GitHub and compile and install it.      And open the log  ,--syncmode=full --mine --devnet --log.merge  --log.path=$path --verbosity 5
